version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/hazelcast-node"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "maven"
    directory: "/jet-jobs"
    schedule:
      interval: "weekly"
      day: "friday"